version: '{build}'
image:
  - Visual Studio 2019
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
install:
  - dotnet --info
  - dotnet restore --disable-parallel
build: off
skip_tags: true
test_script:
  - dotnet test tests -c Debug -f netcoreapp3.1
  - dotnet test tests -c Release -f netcoreapp3.1
  - dotnet test tests -c Debug -f netcoreapp2.1
  - dotnet test tests -c Release -f netcoreapp2.1
after_test:
  - dotnet pack -c Release
artifacts:
  - path: '**\*.nupkg'
