version: '{build}'
image:
  - Visual Studio 2017
environment:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
install:
  - dotnet --info
  - dotnet restore --disable-parallel -s "https://api.nuget.org/v3/index.json" -s "https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"
build: off
test_script:
  - dotnet test tests -c Debug -f netcoreapp2.0
  - dotnet test tests -c Release -f netcoreapp2.0
  - dotnet test tests -c Debug -f netcoreapp1.1
  - dotnet test tests -c Release -f netcoreapp1.1
after_test:
  - dotnet pack -c Release
artifacts:
  - path: '**\*.nupkg'
deploy:
- provider: NuGet
  server: https://www.myget.org/F/nsec/api/v2
  api_key:
    secure: TjONMhmq3TB/PqRQwd5PCT0TAwhJFB2XL3krFHV61JYOQIl75PvXMosF0XJndkya
  skip_symbols: true
