version: 2

workflows:
  version: 2
  test:
    jobs:
      - netcore1.1-centos7.4
      - netcore1.1-debian8.9
      - netcore1.1-fedora24
      - netcore1.1-ubuntu14.04
      - netcore1.1-ubuntu16.04
      - netcore2.0-centos7.4
      - netcore2.0-debian8.9
      - netcore2.0-debian9.2
      - netcore2.0-fedora24
      - netcore2.0-fedora25
      - netcore2.0-fedora26
      - netcore2.0-opensuse42.2
      - netcore2.0-opensuse42.3
      - netcore2.0-ubuntu14.04
      - netcore2.0-ubuntu16.04
      - netcore2.0-ubuntu17.04

shared:
  environment: &environment
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    TERM: dumb
  dotnet-install-1-1: &dotnet-install-1-1
    run:
      name: Installing .NET Core 1.1 Runtime
      command: |
        if [ ! -f ~/dotnet-install.sh ]; then curl -fsLo ~/dotnet-install.sh 'https://dot.net/v1/dotnet-install.sh'; fi
        bash ~/dotnet-install.sh --channel 1.1 --version latest --install-dir ~/.dotnet --no-path --shared-runtime
  dotnet-install-2-0: &dotnet-install-2-0
    run:
      name: Installing .NET Core 2.0 Runtime
      command: |
        if [ ! -f ~/dotnet-install.sh ]; then curl -fsLo ~/dotnet-install.sh 'https://dot.net/v1/dotnet-install.sh'; fi
        bash ~/dotnet-install.sh --channel 2.0 --version latest --install-dir ~/.dotnet --no-path --shared-runtime
  dotnet-install-2-1: &dotnet-install-2-1
    run:
      name: Installing .NET Core 2.1 SDK
      command: |
        if [ ! -f ~/dotnet-install.sh ]; then curl -fsLo ~/dotnet-install.sh 'https://dot.net/v1/dotnet-install.sh'; fi
        bash ~/dotnet-install.sh --channel release/15.5 --version latest --install-dir ~/.dotnet --no-path
        ~/.dotnet/dotnet --info
        echo 'export PATH=~/.dotnet:$PATH' >> $BASH_ENV
  generate-restore-graph: &generate-restore-graph
    run:
      name: Generate restore graph
      command: dotnet msbuild -t:GenerateRestoreGraphFile
      working_directory: tests
      environment:
        RestoreGraphOutputPath: /tmp/restore.json
        Version: 1.0.0-restore
  restore-cache: &restore-cache
    restore_cache:
      keys:
        - 'nuget-packages-{{ checksum "/tmp/restore.json" }}'
        - 'nuget-packages'
  dotnet-restore: &dotnet-restore
    run:
      name: Restore dependencies
      command: dotnet restore -s 'https://api.nuget.org/v3/index.json' -s 'https://dotnet.myget.org/F/dotnet-core/api/v3/index.json' --disable-parallel
  save-cache: &save-cache
    save_cache:
      key: 'nuget-packages-{{ checksum "/tmp/restore.json" }}'
      paths:
        - ~/.nuget/packages
  dotnet-test-debug-1-1: &dotnet-test-debug-1-1
    run:
      name: Run unit tests (Debug)
      command: dotnet test -c Debug -f netcoreapp1.1
      working_directory: tests
  dotnet-test-release-1-1: &dotnet-test-release-1-1
    run:
      name: Run unit tests (Release)
      command: dotnet test -c Release -f netcoreapp1.1
      working_directory: tests
  dotnet-test-debug-2-0: &dotnet-test-debug-2-0
    run:
      name: Run unit tests (Debug)
      command: dotnet test -c Debug -f netcoreapp2.0
      working_directory: tests
  dotnet-test-release-2-0: &dotnet-test-release-2-0
    run:
      name: Run unit tests (Release)
      command: dotnet test -c Release -f netcoreapp2.0
      working_directory: tests

jobs:

  netcore1.1-centos7.4:
    docker:
      - image: centos:7.4.1708
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: yum install -q -y curl ca-certificates libunwind libicu
      - *dotnet-install-1-1
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  netcore1.1-debian8.9:
    docker:
      - image: debian:8.9
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu52
      - *dotnet-install-1-1
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  netcore1.1-fedora24:
    docker:
      - image: fedora:24
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: dnf install -q -y curl ca-certificates findutils tar libunwind libicu
      - *dotnet-install-1-1
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  netcore1.1-ubuntu14.04:
    docker:
      - image: ubuntu:14.04
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu52
      - *dotnet-install-1-1
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  netcore1.1-ubuntu16.04:
    docker:
      - image: ubuntu:16.04
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu55 libcurl3
      - *dotnet-install-1-1
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  netcore2.0-centos7.4:
    docker:
      - image: centos:7.4.1708
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: yum install -q -y curl ca-certificates libunwind libicu
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-debian8.9:
    docker:
      - image: debian:8.9
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu52
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-debian9.2:
    docker:
      - image: debian:9.2
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-fedora24:
    docker:
      - image: fedora:24
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: dnf install -q -y curl ca-certificates findutils tar libunwind libicu
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-fedora25:
    docker:
      - image: fedora:25
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: dnf install -q -y curl ca-certificates findutils libunwind libicu
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-fedora26:
    docker:
      - image: fedora:26
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: dnf install -q -y curl ca-certificates findutils libunwind libicu compat-openssl10
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-opensuse42.2:
    docker:
      - image: opensuse:42.2
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: zypper -q install -y --no-recommends curl ca-certificates tar ncurses-utils libunwind libicu
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-opensuse42.3:
    docker:
      - image: opensuse:42.3
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: zypper -q install -y --no-recommends curl ca-certificates tar ncurses-utils libunwind libicu
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-ubuntu14.04:
    docker:
      - image: ubuntu:14.04
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu52
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-ubuntu16.04:
    docker:
      - image: ubuntu:16.04
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu55 libcurl3
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  netcore2.0-ubuntu17.04:
    docker:
      - image: ubuntu:17.04
    environment: *environment
    steps:
      - run:
          name: Install prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu57
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0
