version: 2
jobs:
  build:
    working_directory: ~/nsec
    docker:
      - image: microsoft/dotnet:1.1-sdk
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: dotnet restore
          command: dotnet restore --source "https://api.nuget.org/v3/index.json" --source "https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"
          working_directory: ~/nsec/tests
      - run:
          name: dotnet test
          command: dotnet test
          working_directory: ~/nsec/tests
