version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.0-sdk
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore --source "https://api.nuget.org/v3/index.json" --source "https://dotnet.myget.org/F/dotnet-core/api/v3/index.json" --source "https://dotnet.myget.org/F/roslyn/api/v3/index.json"
      - run:
          name: Run unit tests (Debug)
          command: dotnet test tests -c Debug
      - run:
          name: Run unit tests (Release)
          command: dotnet test tests -c Release
      - run:
          name: Create NuGet package
          command: dotnet pack -c Release -o ~/artifacts/
      - store_artifacts:
          path: ~/artifacts/
          destination: /
