version: 2
jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    environment:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - checkout
      - run:
          name: Restore dependencies
          command: dotnet restore --source "https://api.nuget.org/v3/index.json" --source "https://dotnet.myget.org/F/dotnet-core/api/v3/index.json"
      - run:
          name: Run unit tests (Debug)
          command: dotnet test -c Debug -f netcoreapp1.1
          working_directory: tests
      - run:
          name: Run unit tests (Release)
          command: dotnet test -c Release -f netcoreapp1.1
          working_directory: tests
      - run:
          name: Create NuGet package
          command: dotnet pack -c Release -o ~/artifacts/
          working_directory: src
      - store_artifacts:
          path: ~/artifacts/
          destination: /
