version: 2

workflows:
  version: 2
  test:
    jobs:
      - centos7.4:
          requires:
            - macos-xcode9.2
      - debian8.10:
          requires:
            - macos-xcode9.2
      - debian9.3:
          requires:
            - macos-xcode9.2
      - fedora26:
          requires:
            - macos-xcode9.2
      - fedora27:
          requires:
            - macos-xcode9.2
      - opensuse42.3:
          requires:
            - macos-xcode9.2
      - ubuntu14.04:
          requires:
            - macos-xcode9.2
      - ubuntu16.04:
          requires:
      - ubuntu17.10:
          requires:
            - macos-xcode9.2
      - macos-xcode9.2:
          requires:
            - ubuntu16.04

shared:
  environment: &environment
    DOTNET_CLI_TELEMETRY_OPTOUT: 1
    DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
    TERM: dumb
  dotnet-install-1-1: &dotnet-install-1-1
    run:
      name: Install .NET Core 1.1 Runtime
      command: |
        if [ ! -f ~/dotnet-install.sh ]; then curl -fsLo ~/dotnet-install.sh 'https://dot.net/v1/dotnet-install.sh'; fi
        bash ~/dotnet-install.sh --channel 1.1 --version latest --install-dir ~/.dotnet --no-path --shared-runtime
  dotnet-install-2-0: &dotnet-install-2-0
    run:
      name: Install .NET Core 2.0 Runtime
      command: |
        if [ ! -f ~/dotnet-install.sh ]; then curl -fsLo ~/dotnet-install.sh 'https://dot.net/v1/dotnet-install.sh'; fi
        bash ~/dotnet-install.sh --channel 2.0 --version latest --install-dir ~/.dotnet --no-path --shared-runtime
  dotnet-install-2-1: &dotnet-install-2-1
    run:
      name: Install .NET Core 2.1 SDK
      command: |
        if [ ! -f ~/dotnet-install.sh ]; then curl -fsLo ~/dotnet-install.sh 'https://dot.net/v1/dotnet-install.sh'; fi
        bash ~/dotnet-install.sh --channel release/2.1.3xx --version latest --install-dir ~/.dotnet --no-path
        ~/.dotnet/dotnet --info
        echo 'export PATH=~/.dotnet:$PATH' >> $BASH_ENV
  generate-restore-graph: &generate-restore-graph
    run:
      name: Generate Dependency Graph
      command: dotnet msbuild -t:GenerateRestoreGraphFile
      working_directory: tests
      environment:
        RestoreGraphOutputPath: /tmp/restore.json
        Version: 1.0.0-restore
  restore-cache: &restore-cache
    restore_cache:
      keys:
        - 'linux-nuget-packages-{{ checksum "/tmp/restore.json" }}'
        - 'linux-nuget-packages'
  restore-cache-macos: &restore-cache-macos
    restore_cache:
      keys:
        - 'macos-nuget-packages-{{ checksum "/tmp/restore.json" }}'
        - 'macos-nuget-packages'
  dotnet-restore: &dotnet-restore
    run:
      name: Restore Dependencies
      command: dotnet restore --disable-parallel -s 'https://api.nuget.org/v3/index.json' -s 'https://dotnet.myget.org/F/dotnet-core/api/v3/index.json'
  save-cache: &save-cache
    save_cache:
      key: 'linux-nuget-packages-{{ checksum "/tmp/restore.json" }}'
      paths:
        - ~/.nuget/packages
  save-cache-macos: &save-cache-macos
    save_cache:
      key: 'macos-nuget-packages-{{ checksum "/tmp/restore.json" }}'
      paths:
        - ~/.nuget/packages
  dotnet-test-debug-1-1: &dotnet-test-debug-1-1
    run:
      name: Run unit tests (Debug) (.NET Core 1.1)
      command: dotnet test tests -c Debug -f netcoreapp1.1
  dotnet-test-release-1-1: &dotnet-test-release-1-1
    run:
      name: Run unit tests (Release) (.NET Core 1.1)
      command: dotnet test tests -c Release -f netcoreapp1.1
  dotnet-test-debug-2-0: &dotnet-test-debug-2-0
    run:
      name: Run unit tests (Debug) (.NET Core 2.0)
      command: dotnet test tests -c Debug -f netcoreapp2.0
  dotnet-test-release-2-0: &dotnet-test-release-2-0
    run:
      name: Run unit tests (Release) (.NET Core 2.0)
      command: dotnet test tests -c Release -f netcoreapp2.0
  dotnet-test-debug-2-1: &dotnet-test-debug-2-1
    run:
      name: Run unit tests (Debug) (.NET Core 2.1)
      command: dotnet test tests -c Debug -f netcoreapp2.1
  dotnet-test-release-2-1: &dotnet-test-release-2-1
    run:
      name: Run unit tests (Release) (.NET Core 2.1)
      command: dotnet test tests -c Release -f netcoreapp2.1

jobs:

  centos7.4:
    docker:
      - image: centos:7.4.1708
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: yum install -q -y curl ca-certificates libunwind libicu
      - *dotnet-install-1-1
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  debian8.10:
    docker:
      - image: debian:8.10
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu52
      - *dotnet-install-1-1
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  debian9.3:
    docker:
      - image: debian:9.3
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  fedora26:
    docker:
      - image: fedora:26
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: dnf install -q -y curl ca-certificates findutils libunwind libicu compat-openssl10
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  fedora27:
    docker:
      - image: fedora:27
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: dnf install -q -y curl ca-certificates findutils libunwind libicu compat-openssl10
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  opensuse42.3:
    docker:
      - image: opensuse:42.3
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: zypper -q install -y --no-recommends curl ca-certificates tar ncurses-utils libunwind libicu
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  ubuntu14.04:
    docker:
      - image: ubuntu:14.04
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu52
      - *dotnet-install-1-1
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  ubuntu16.04:
    docker:
      - image: ubuntu:16.04
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu55 libcurl3
      - *dotnet-install-1-1
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1

  ubuntu17.10:
    docker:
      - image: ubuntu:17.10
    environment: *environment
    steps:
      - run:
          name: Install Prerequisites
          command: |
            apt-get -qq update
            apt-get -qq install --yes --no-install-recommends curl ca-certificates apt-transport-https gettext libunwind8 libicu57
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache
      - *dotnet-restore
      - *save-cache
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0

  macos-xcode9.2:
    macos:
      xcode: "9.2.0"
    environment: *environment
    steps:
      - *dotnet-install-1-1
      - *dotnet-install-2-0
      - *dotnet-install-2-1
      - checkout
      - *generate-restore-graph
      - *restore-cache-macos
      - *dotnet-restore
      - *save-cache-macos
#     - *dotnet-test-debug-2-1
#     - *dotnet-test-release-2-1
      - *dotnet-test-debug-2-0
      - *dotnet-test-release-2-0
      - *dotnet-test-debug-1-1
      - *dotnet-test-release-1-1
